config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name, case_sensitive: false
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_current_user, only: [:edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.page(params[:page]).per(5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path , status: :see_other
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_current_user
    unless current_user == @article.user || current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.page(params[:page]).per(5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "New category successfully created"
      redirect_to @category
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "The category is successfully updated"
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def index
    @categories = Category.page(params[:page]).per(5)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = " Only admins can perform that action"
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Your are successfully logged in"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are successfully logged out"
    redirect_to root_path, status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_current_user, only: [:edit, :update, :destroy]

  def index
    @users = User.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the AlphaBlog #{@user.username}, you have successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and its all associated articles have been deleted successfully"
    redirect_to articles_path, status: :see_other
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.page(params[:page]).per(5)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_current_user
    unless current_user == @user || current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end


end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<h3 class="text-center mt-4">Articles</h3>

<div class="container listing-container">
  <% obj.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="container">
          <div class="card text-center shadow-sm mb-5 bg-light rounded">
            <div class="card-header fst-italic">
              <% if article.user %>
                by <%= link_to article.user.username, user_path(article.user) %>
              <% end %>
              <% if article.categories.any? %>
                <div class="mt-2"><%= render article.categories %></div>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to article.title, article_path(article), class: 'text-success' %></h5>
              <p class="card-text"><%= truncate(article.description, length: 100) %></p>
              <%= link_to 'View',
                          article_path(article),
                          data: { turbo_method: :get },
                          class: "btn btn-outline-success" %>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to 'Edit',
                            edit_article_path(article),
                            class: "btn btn-outline-info" %>
                <%= link_to 'Delete',
                            article_path(article),
                            data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                            class: "btn btn-outline-danger" %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>
                <%= "created at #{time_ago_in_words(article.created_at)} ago." %>
                <%= article.created_at == article.updated_at ? "" : "edited at #{time_ago_in_words(article.updated_at)} ago." %>
              </small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= render 'layouts/pagination', obj: obj %>

app/views/articles/_form.html.erb
<div class="row justify-content-center" id="form-container">
  <div class="col-10">
    <%= render "articles/shared/errors", obj: @article %>
    <%= form_with(model: @article, class: 'shadow bg-info rounded my-3 px-3 py-5', local: true) do |f| %>

      <div class="container">
        <form>
          <div class="row mb-3">
            <%= f.label :title, class: 'col-2 col-form-label text-light' %>
            <div class="col-sm-10">
              <%= f.text_field :title,
                               class: 'form-control shadow-sm rounded',
                               placeholder: 'Title of article' %>
            </div>
          </div>

          <div class="row mb-3">
            <%= f.label :description, class: 'col-2 col-form-label text-light' %>
            <div class="col-sm-10">
              <%= f.text_area :description, rows: 10,
                              class: 'form-control shadow-sm rounded',
                              placeholder: 'Description of article' %>
            </div>
          </div>

          <div class="row mb-3">
            <%= f.label :categories, class: 'col-2 col-form-label text-light' %>
            <div class="col-sm-10">
              <%= f.collection_select(:category_ids, Category.all, :id, :name,
                                      { prompt: "Make your selection from the list below (can be empty)" },
                                      { multiple: true, size: 3, class: "form-select shadow-sm rounded" }) %>
            </div>
          </div>

          <div class="row justify-content-center">
            <%= f.submit class: 'col-2 mt-3 btn btn-outline-light btn-lg' %>
          </div>
        </form>
      </div>
    <% end %>
  </div>
  <div class="text-center">
    <%= link_to '[ Go back ]', articles_path, class: 'text-info'%>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit a new article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show shadow-sm rounded" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>

<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="container">
      <div class="card text-center shadow-sm mb-5 bg-light rounded">
        <div class="card-header fst-italic">
          by <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
            <div class="mt-2"><%= render @article.categories %></div>
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-start px-4">
            <p><%= simple_format(@article.description) %></p>
          </div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit',
                        edit_article_path(@article),
                        class: "btn btn-outline-info" %>
            <%= link_to 'Delete',
                        article_path(@article),
                        data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                        class: "btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>
            <%= "created at #{time_ago_in_words(@article.created_at)} ago." %>
            <%= @article.created_at == @article.updated_at ? "" : "edited at #{time_ago_in_words(@article.updated_at)} ago." %>
          </small>
        </div>
      </div>
    </div>
  </div>
  <%= link_to '[ Go back ]', articles_path, class: 'text-center text-info' %>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill text-bg-info mr-1" %>

app/views/categories/_form.html.erb
<%= render "articles/shared/errors", obj: @category %>

<%= form_with(model: @category, class: 'shadow bg-info rounded my-3 px-3 py-5', local: true) do |f| %>
  <div class="container">
    <form>

      <div class="row mb-3">
        <%= f.label :name, 'New category name', class: 'col-2 col-form-label text-light' %>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control shadow-sm rounded', placeholder: 'Enter a name' %>
        </div>
      </div>

      <div class="row justify-content-center">
        <%= f.submit class: 'col-2 mt-3 btn btn-outline-light btn-lg' %>
      </div>

    </form>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>

<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'form' %>
  </div>
</div>

<div class="text-center mb-3">
  <%= link_to '[ Go back ]', category_path(@category), class: 'text-info'%>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="container listing-container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="container">
          <div class="card text-center shadow-sm mb-5 bg-light rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.name, category_path(category), class: 'text-success' %></h5>
              <p class="card-text"><%= pluralize(category.articles.count, 'article') %></p>
            </div>
            <div class="card-footer text-muted">
              <small>
                <%= "created at #{time_ago_in_words(category.created_at)} ago." %>
                <%= category.created_at == category.updated_at ? "" : "edited at #{time_ago_in_words(category.updated_at)} ago." %>
              </small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= render 'layouts/pagination', obj: @categories %>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<div class="row justify-content-center">
  <div class="col-10">

    <%= render "articles/shared/errors", obj: @category %>

    <%= form_with(model: @category, class: 'shadow bg-info rounded my-3 px-3 py-5', local: true) do |f| %>
      <div class="container">
        <form>

          <div class="row mb-3">
            <%= f.label :name, 'New category name', class: 'col-2 col-form-label text-light' %>
            <div class="col-sm-10">
              <%= f.text_field :name, class: 'form-control shadow-sm rounded', placeholder: 'Enter a name' %>
            </div>
          </div>

          <div class="row justify-content-center">
            <%= f.submit class: 'col-2 mt-3 btn btn-outline-light btn-lg' %>
          </div>

        </form>
      </div>
    <% end %>
  </div>
</div>

<div class="text-center mb-3">
  <%= link_to '[ Go back ]', articles_path, class: 'text-info'%>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4"><%= @category.name %></h1>

<div class="text-center mt-4">
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'Edit category', edit_category_path, class: "btn btn-outline-info" %>
  <% end %>
</div>

<%= render 'articles/article', obj: @articles %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-3 bg-dark text-white-50 fixed-bottom">
  <div class="container text-center">
    <small>Copyright &copy; kj7kt</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class=" container alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert" >
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="閉じる"></button>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical text-white" viewBox="0 0 16 16">
            <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
          </svg>
        </span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Bloggers', users_path, class: 'nav-link' %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <%= link_to 'Create new article', new_article_path, class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'View articles', articles_path, class: 'dropdown-item' %>
            <li>
              <hr class="dropdown-divider">
            </li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? && current_user.admin? %>
              <%= link_to 'Create a new category', new_category_path, class: 'dropdown-item' %>
            <% end %>
            <%= link_to 'View categories', categories_path, class: 'dropdown-item' %>
          </ul>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profile [<%= current_user.username %>]<%= '(Admin)' if current_user.admin? %>
            </a>
            <ul class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
              <%= link_to 'View your profile',
                          user_path(current_user),
                          class: 'dropdown-item' %>
              <%= link_to 'Edit your profile',
                          edit_user_path(current_user),
                          class: 'dropdown-item' %>
              <%= link_to 'Delete your profile',
                          user_path(current_user),
                          date: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                          class: 'dropdown-item text-danger' %>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out',
                        logout_path,
                        data: { turbo_method: :delete,
                                turbo_confirm: "Are you sure?" },
                        class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in',
                        login_path,
                        data: { turbo_method: :create },
                        class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_pagination.html.erb
<div class="apple_pagination fixed-bottom mt-auto">
  <%= paginate obj %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column min-vh-100" id='page-content'>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>

<%= link_to 'Home', root_path %> |
<%= link_to 'Articles', articles_path %>

app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron bg-light p-4 p-sm-5 my-4 rounded text-center text-white">
    <h1 class="display-4">Alpha Blog</h1>
    <p class="lead">これはKJ7KTのエンジニアとしての最初の一歩の単純なブログサイトです。右上の検索バーはまだ機能しません。</p>
    <hr class="my-4">
    <p>会員登録すれば誰でも記事を投稿することができます。</p>
    <%= link_to '登録する', signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div><!-- /.container -->

<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50 fixed-bottom">
  <div class="container text-center">
    <small>Copyright &copy; kj7kt</small>
  </div>
</footer>

app/views/users/_form.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <%= render "articles/shared/errors", obj: @user %>
    <%= form_with(model: @user, class: 'shadow bg-info rounded my-3 px-3 py-5', local: true) do |f| %>

      <div class="container">
        <form>
          <div class="row mb-3">
            <%= f.label :username, class: 'col-2 col-form-label text-light' %>
            <div class="col-sm-10">
              <%= f.text_field :username, class: 'form-control shadow-sm rounded', placeholder: 'Enter a username' %>
            </div>
          </div>

          <div class="row mb-3">
            <%= f.label :email, class: 'col-2 col-form-label text-light' %>
            <div class="col-sm-10">
              <%= f.email_field :email, class: 'form-control shadow-sm rounded', placeholder: 'Enter your email address' %>
            </div>
          </div>

          <div class="row mb-3">
            <%= f.label :password, class: 'col-2 col-form-label text-light' %>
            <div class="col-sm-10">
              <%= f.password_field :password, class: 'form-control shadow-sm rounded', placeholder: 'Choose a password' %>
            </div>
          </div>

          <div class="row justify-content-center">
            <%= f.submit(@user.new_record? ? 'Sign up' : 'Update account', class: 'col-2 mt-3 btn btn-outline-light btn-lg') %>
          </div>
        </form>
      </div>
    <% end %>
  </div>
  <div class="text-center mb-3">
    <%= link_to '[ Go back ]', articles_path, class: 'text-info'%>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>

<div class="container listing-container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="container">
          <div class="card text-center shadow-sm mb-5 bg-light rounded">
            <div class="card-header fst-italic">
              by <%= link_to user.username, user %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= link_to gravatar_for(user, size: 150) %></h5>
              <p class="card-text"><%= pluralize(user.articles.count, 'article') %></p>
              <%= link_to 'View profile',
                          user_path(user),
                          data: { turbo_method: :get },
                          class: "btn btn-outline-success" %>
              <% if logged_in? %>
                <% if user == current_user %>
                  <%= link_to 'Edit profile',
                              edit_user_path(user),
                              class: "btn btn-outline-info" %>
                <% end %>
                <% if current_user.admin? %>
                  <%= link_to 'Delete profile',
                              user_path(user),
                              data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete user?' },
                            class: "btn btn-outline-danger" %>
                <% end %>
              <% end %>
            </div>
            <div class="card-footer text-muted">
              <small>
                <%= "Joined #{time_ago_in_words(user.created_at)} ago." %>
              </small>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= render 'layouts/pagination', obj: @users %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for AlphaBlog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<div class="text-center mt-4">
  <% if logged_in? && @user == current_user %>
    <%= link_to 'Edit your profile', edit_user_path, class: "btn btn-outline-info" %>
  <% end %>
</div>

<%= render 'articles/article', obj: @articles %>